export const jobs = {
  softwareengineer: 'Software Engineer',
  productmanager: 'Product Manager',
  sdet: 'SDET',
  machinelearningengineer: 'Machine Learning Engineer',
  director: 'Director',
  leadengineer: 'Lead Engineer',
  seniorengineer: 'Senior Engineer',
  memberoftechnicalstaff: 'Member of Technical Staff',
  principalengineer: 'Principal Engineer',
  functionalconsultant: 'Functional Consultant',
  uxdesigner: 'UX Designer',
  dealdeskmanager: 'Deal Desk Manager',
  technicalsupportengineer: 'Technical Support Engineer',
  accountant: 'Accountant',
  productdeliverymanager: 'Product Delivery Manager',
};
