export const langs: {
  locale: string;
  name: string;
}[] = [
  { locale: 'en', name: 'English' },
  { locale: 'it', name: 'Italiano' },
  { locale: 'es', name: 'Español' },
  { locale: 'fr', name: 'Français' },
  { locale: 'pt', name: 'Português' },
  { locale: 'nb', name: 'Norsk' },
  { locale: 'de', name: 'Deutsch' },
  { locale: 'ja', name: '日本語' },
  { locale: 'ms', name: 'Bahasa melayu' },
  { locale: 'zh-CN', name: '中文 (简体)' },
  { locale: 'zh-TW', name: '中文 (繁體)' },
  { locale: 'ko', name: '한국어' },
  { locale: 'th', name: 'ภาษาไทย' },
  { locale: 'hr', name: 'Hrvatski' },
  { locale: 'uk', name: 'Yкраїнська' },
  { locale: 'nl', name: 'Nederlands' },
  { locale: 'pl', name: 'Polski' },
  { locale: 'el', name: 'Ελληνικά' },
  { locale: 'hu', name: 'Magyar' },
  { locale: 'cs', name: 'čeština' },
  { locale: 'tr', name: 'Türkçe' },
  { locale: 'ru', name: 'Pусский' },
  { locale: 'ht', name: 'Haitian' },
  { locale: 'he', name: 'עברית' },
  { locale: 'pt-BR', name: 'Brazilian Português' },
  { locale: 'da', name: 'Dansk' },
  { locale: 'fi', name: 'Suomi' },
  { locale: 'sv', name: 'Svenska' },
];
